version: '3.8'
services:
  datenbank:
    image: postgres:15
    container_name: datenbank
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=5432
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  uploader:
    image: maximiliangt500/uploader
    container_name: uploader
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/opt/uploader/uploads
      - ./public:/opt/uploader/public
    tmpfs: /tmp
    tty: true
    environment:
      - NODE_ENV=production
      
      - AUDIO_FORMATS=.mp3,.wav,.ogg,.aac,.flac # Unterstützte Audioformate
      - VIDEO_FORMATS=.mp4,.avi,.mkv,.mov,.wmv # Unterstützte Videoformate
      - IMAGE_FORMATS=.jpg,.jpeg,.png,.bmp,.svg,.webp,.tiff # Unterstützte Bildformate

      - BASE_URL=http://localhost:3000 # Basis-URL der Anwendung
      - PORT=3000 # Port der Anwendung
      - JWT_TOKEN=CHANGEME # Zufälliger Token
      - REMOVE_METADATA=true # Sollen Metadaten, wie der Standort entfernt werden nach dem Upload? (Dies verringert die Leistung.)
      - USE_PREVIEW=true # Soll ein Preview Bild erstellt werden?

      - SITE_TITLE=EXAMPLE # Meta-Tag title
      - SITE_FAVICON=/assets/favicon.png # Path zur .png-Datei oder zu einer .png-URL
      - OG_TITLE=EXAMPLE # Meta-Tag og:title
      - OG_DESCRIPTION=EXAMPLE # Meta-Tag og:description
      - THEME_COLOR=&dominantColor # Meta-Tag theme-color - wenn &dominantColor als themecolor genommen wird, ist das Embed in der Dominanten Farbe der Datei

      - DATABASE_HOST=datenbank # Postgres - Hostname (Wenn Docker genutzt wird, nicht ändern.)
      - DATABASE_PORT=5432 # Postgres - Port (Wenn Docker genutzt wird, nicht ändern.)
      - DATABASE_USER=postgres # Postgres - Datenbank Nutzer (Wenn Docker genutzt wird, nicht ändern.)
      - DATABASE_PASSWORD=postgres # Postgres - Datenbank Passwort (Wenn Docker genutzt wird, nicht ändern.)
      - DATABASE_DATABASE=postgres # Postgres - Datenbank (Wenn Docker genutzt wird, nicht ändern.)

      - AUTHOR_URL=https://example.com # OEmbed
      - AUTHOR_NAME=EXAMPLE # OEmbed
      - PROVIDER_NAME=EXAMPLE.COM # OEmbed
      - PROVIDER_URL=https://example.com # OEmbed

      - USE_DOMINANT_COLOR=true # Soll die Dominate Farbe des Bildes für den Shadow genutzt werden? (dann true) Sollte lieber eine Static Farbe genutzt werden? (dann false und fülle dominantColorStatic aus)
      - DOMINANT_COLOR_STATIC=#ffffff # Diese Farbe wird anstelle der Dominanten Farbe genutzt. (#HEXCOLOR)
      - BOX_SHADOW_COLOR=#ffffff # Wird Angewand, wenn die Datei kein Bild ist. (#HEXCOLOR)

      - COPYRIGHT_TEXT=&copy; 2023 EXAMPLE - All Rights Reserved # Copyright Text

      - DISCORD_WEBHOOK_NAME=Datei-Uploader # Dies ist der Name der Webhook
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/XXXX/XXXX # Für Discord-Webhook logging
      - DISCORD_WEBHOOK_SUCCESS_COLOR=0x03fc28 # Embed-Farbe bei INFO Logs (0xHEXCOLORCODEOHNE-#)
      - DISCORD_WEBHOOK_ERROR_COLOR=0xfc0303 # Embed-Farbe bei ERROR Logs (0xHEXCOLORCODEOHNE-#)

      - REDIRECT_URL=https://example.com # Wohin soll man Weitergeleitet werden, wenn man / aufruft?
    #env_file:
    #  - .env # Nenne example.env zu .env um!
    depends_on:
      - 'datenbank'