version: '3.8'
services:
  datenbank:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 4hbyjRe3CJWmgkNBkCJxfEgLzxNJ6q6npqm6froM5mKmVehg7aq6NKsvWeNh8iJX
      MYSQL_DATABASE: uploader
      MYSQL_USER: uploader
      MYSQL_PASSWORD: 8RAcsRYSj75nePoCvzatZeqtaeyd8p7C4EtyWx78d2XwdJqa7c5SLuWqojWuz3yd
    volumes:
      - data:/var/lib/mysql
      - ./dev/mariadb:/docker-entrypoint-initdb.d
    ports:
      - "36432:3306" # Oft ist der Standart Port 3306 belegt. Die Portanpassung verhindert dies.
  uploader:
    build: .
    container_name: uploader-docker
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/opt/uploader/uploads
      - ./public:/opt/uploader/public
      - type: bind
        source: ./config.js
        target: /opt/uploader/config.js
    tmpfs: /tmp
    tty: true
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=debug
      - FORCE_COLOR=3
    links:
      - datenbank
volumes:
  data:
